#steps:
#- name: 'docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]


steps:

- name: python
  id: "Run Unit Testing"
  entrypoint: python
  #  args: [ "pyexample.py" ]
  args: ["-m", "pip", "install", "pytest"]


