#steps:
#- name: 'docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]


steps:

- name: python
  id: "Step1"
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]

- name: python
  id: "Step2"
  entrypoint: python
  args: ["--version"] 
  waitFor: ["Step1"]


