#steps:
#- name: 'docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]




steps:
- name: python
  entrypoint: python
  args: ["-m", "pytest", "pyexample.py" ]

images:
- 'gcr.io/$PROJECT_ID/python-test-image'

