#steps:
#- name: 'docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]




steps:
- name: python
  args:
    - pip
    - install
    - pytest
- name: python
  args:
    - pytest
    - '-s'
    - GCP/Templates/Functions/FunctionTemplatePython3.9
images:
- 'gcr.io/$PROJECT_ID/python-test-image'

