#steps:
#- name: 'docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]


steps:

- name: python
  id: "Will it blend?"
  entrypoint: "bash"
  args:
  - '-c' # pass what follows as a command to bash
  - |
    python -m pip install pytest
    pytest -s pyexample.py



